name: luxury_restaurant_app
description: A luxury restaurant mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  web_socket_channel: ^3.0.3
  emailjs: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  just_audio: ^0.9.36
  audioplayers: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/FoodItems/
    - assets/images/FoodItems/GrilledSirloinSteak.png
    - assets/images/
    - assets/sounds/click.mp3
    - assets/images/Anolini with Mushroom Ragout and Wild Garlic and Mushroom Sauce Recipe.jpg
    - assets/images/Artichoke Heart & Ricotta Stack – A Vegetarian Fine Dining Recipe.jpg
    - assets/images/Beetroot Carpaccio with Citrus-Glazed Tempeh_ A Fresh and Elegant Vegan Appetizer.jpg
    - assets/images/Crispy Lotus Root & Root Vegetable Medley over Hummus.jpg
    - assets/images/Deconstructed Poached Egg with Carrot Veloutés.jpg
    - assets/images/Gourmet Tofu with Roasted Mushrooms.jpg
    - assets/images/Roasted Mission Fig & Whipped Ricotta Crostini.jpg
    - assets/images/Tartare Mille-Feuille with Parmesan Tuile.jpg
    - assets/images/The Summer Bloom Burrata Salad.jpg
    - assets/images/Vanilla Bean Panna Cotta with Raspberry Coulis & Isomalt Cage.jpg


