name: luxury_restaurant_app
description: A luxury restaurant mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  web_socket_channel: ^3.0.3
  emailjs: ^4.0.0
  provider:
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  just_audio: ^0.9.36
  audioplayers: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/FoodItems/
    - assets/images/FoodItems/GrilledSirloinSteak.png
    - assets/images/
    - assets/sounds/click.mp3


